version: '3'

services:
    postgres:
        image: postgres:12.2
        container_name: wardrobe-app_postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=wardrobe_app
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - wardrobe-app_postgres-data:/var/lib/postgresql/data
    redis:
        image: redis:6-alpine
        container_name: wardrobe-app_redis
        ports:
            - 6379:6379

volumes:
    wardrobe-app_postgres-data:
